### ISSUE TITLE
Google backup transport

### ISSUE THREAD

**Issue by GolamRabbany123** [dreamwhite/gsync_adapters_for_magisk#1]
It syncs 2-3 min late.
You should include Google backup transport app 

After installing Google backup transport is syncs instantaniously.

**Comment by GolamRabbany123** [comment]
Really glad to find your reply.

Google backup transport is needed for some devices.I am using COVUS OS (Android 10) on J5 with microg.

I got this Google backup transport from Open Gapps.When trying to get Google calendar sync and Contact sync from the open g apps this Google backup transport came as a byproduct for sync .

Tested the release you mentioned.My calendar sync working fine 😊.Contact sync not working at all. Checked all apps .There is no contact sync app in system app. The APKMIRROR contact sync app you are using is not compatible with all devices. 
port the contract sync  from Open GAPPS micro or nano or else it won't work in many of the devices.

**Comment by dreamwhite** [comment]
Sweet, thank you so much. I didn't know where to extract those apk since I blindly unzipped opengapps (nano) and didn't found them. Tomorrow I'll check first if the chinese rocket won't destroy my house, then I'll make another release.
Are you willing to help me through testing since on my side every Google SyncAdapter I tested (both from opengapps and apk mirror releases) worked?
Many thanks and have a nice day ^^

**Comment by GolamRabbany123** [comment]
I've tried out many versions of Google Contact Sync from APKMIRROR. from my end some apps say unable to phase info and just don't install and some apps install but there is no contact sync.
![Screenshot_20210509-060425_Settings](https://user-images.githubusercontent.com/43527678/117556633-c1e74000-b08c-11eb-8c27-0b082e964013.png)

Calendar sync working fine but contact sync problem goes on.

Have a nice life .May Allah bless you.

**Comment by GolamRabbany123** [comment]
some workaround :-
I flashed the new magisk module you gave me.
The Calendar sync ok 
Contact sync not working.

Open GApps updated the pico arm a few days back.So,I again downloaded pico arm open GApps.
From there extracted Contact.tar.lz then converters it to zip with online cloud conversation. There found Contact sync adapter (2.61MB).

Went to root/system/app/Google contact sync adapter ----> found Contact sync adapter (1.23MB) replaced it with the 2.61MB app .
Now everything is working fine.

I tried to modify the module zip same as the system but magisk shows Unzip error.

**Comment by GolamRabbany123** [comment]
I am leaving you with the Contract Sync Adapter (2.61MB).So that it is easier for you to make the module.

https://mega.nz/file/So8QjQYa#s2-H4HGiivXBSNncoShM60a1sYdQC2pk1IgHm0kLWKQ

**Comment by trohnjavolta** [comment]
@dreamwhite Had the same problem as @GolamRabbany123 , calendar sync working, contacts sync not working. Checked date of the latest comment here with the apk, checked release date. Ok, it's not in the release :) 
Tried the apk from the latest comment and it worked!
Could you add that apk in your magisk module and release a new version? That would spare others the hassle of figuring out how to make contacts sync work.

**Comment by dreamwhite** [comment]
Yeah sure, I'll create a test release. Can you please confirm it that on your side it works?

**Comment by dreamwhite** [comment]
@trohnjavolta I've created a test release. Can you please confirm that it is working on your side?
Here's the link to download it: [release](https://github.com/dreamwhite/gsync_adapters_for_magisk/releases/download/69420-v420/dreamwhite_gsync.zip)

**Comment by trohnjavolta** [comment]
> @trohnjavolta I've created a test release. Can you please confirm that it is working on your side?
> Here's the link to download it: [release](https://github.com/dreamwhite/gsync_adapters_for_magisk/releases/download/69420-v420/dreamwhite_gsync.zip)

Thx for the fast release, I can confirm the test release works perfectly fine for me. Just for context, I'm using lineageos 17.1 microg version on a Galaxy S7.

**Comment by dreamwhite** [comment]
Nice!
May I ask you if you dirty flashed the beta release or you just clean flashed?
I clean flashed the module and it worked

**Comment by trohnjavolta** [comment]
I clean flashed it. had to resore a twrp backup before cause I messed up my playstore.

**Comment by dreamwhite** [comment]
> had to resore a twrp backup before cause I messed up my playstore.

Oh okay, but did the module caused that mess somehow or what? 😅
Sorry for those questions but if there's the need of pointing out to clean flash the module (basically removing the module and reinstalling it again) I need to know it

**Comment by trohnjavolta** [comment]
No, not at all :D I deleted data of the playstore cause in app purchases weren't recognized.

**Comment by dreamwhite** [comment]
> No, not at all :D I deleted data of the playstore cause in app purchases weren't recognized.

Ohhhh okay, then I don't think that the Magisk module can interfere 😅.
I've changed the status of the test release from draft to release.

Users who are still experiencing weird issues can write in this issue
